### ISSUE TITLE
Unowned self "attempted to retain deallocated object"

### ISSUE THREAD

**Issue by apparition47** [ShengHuaWu/MVVMInSwift#1]
I'm using your approach in a Swift 3 project and I'm getting the following after I switch *ViewControllers*:
```
libswiftCore.dylib`_swift_abortRetainUnowned:
    0x10146473c <+0>:  adr    x8, #0x90de4              ; gCRAnnotations
    0x101464740 <+4>:  nop    
    0x101464744 <+8>:  adr    x9, #0x2b8a5              ; "attempted to retain deallocated object"
    0x101464748 <+12>: nop    
    0x10146474c <+16>: str    x9, [x8, #0x8]
->  0x101464750 <+20>: brk    #0x1
```

It appears to be happening here with the `[unowned self]` reference:
```swift
        viewModel = DemoViewModel { [unowned self] (state) in
                // ...
                self.tableView.beginUpdates()
                // ...
            }
        }
```

Seems like I have to use `[weak self]` with `self?.tableView.beginUpdates()` in my case. Any ideas?

**Comment by ShengHuaWu** [comment]
Hi @apparition47,

Sorry for late reply.

You are right. 
If your view controller is dismissed and deallocated, there will be a retain cycle.
It is better to use `[weak self]` instead of `[unowned self]` in a general case.

Thank you for your comment.
